/* Correção definitiva: o menu usa este fluxo, sem depender das funções antigas de rodada. */
const AYLA_RANDOM={order:[]};
function aylaStartGame(game){
  AYLA_RANDOM.order=shuffle(games[game].rounds.map((_,i)=>i));
  state.game=game;state.index=0;state.score=0;state.locked=false;state.speaking=false;state.memory=null;
  window.speechSynthesis?.cancel();
  if(animalPlayer){animalPlayer.pause();animalPlayer=null}
  $('menu').classList.remove('active');$('game').classList.add('active');
  setTimeout(()=>aylaPresentRound(),120);
}
function aylaData(){const g=games[state.game];const i=AYLA_RANDOM.order[state.index]??state.index;return g.rounds[i]}
function aylaQuestionText(){const d=aylaData(),g=games[state.game];if(state.game==='numbers'||state.game==='letters')return g.q(d);const q={animals:'Que animal é esse?',colors:'Que cor é essa?',fruits:'Que fruta é essa?',vehicles:'Que veículo é esse?',objects:'Que objeto é esse?',shapes:'Que forma é essa?',vegetables:'Que legume ou verdura é essa?'};if(q[state.game])return q[state.game];if(state.game==='sounds')return 'Ouça o som! Qual animal faz esse som?';if(state.game==='memory')return 'Encontre os pares!';if(state.game==='different')return 'Qual é o diferente?';if(state.game==='counting')return 'Quantos objetos você vê?';if(state.game==='sequence')return 'O que vem depois?';return `Qual é o ${d[2].toLowerCase()}?`}
function aylaOptions(){const d=aylaData(),g=games[state.game],n=difficulty();if(state.game==='numbers'||state.game==='letters'){const p=g.rounds.filter(x=>x!==d);return shuffle([d,...shuffle(p).slice(0,n-1)])}if(namedGames.has(state.game)||state.game==='sounds'){const p=shuffle(g.rounds.filter(x=>x[1]!==d[1]));return shuffle([d,...p.slice(0,n-1)]).map(x=>({emoji:x[0],label:x[1],key:x[1]}))}if(state.game==='different')return n===2?shuffle([d[2],d[0]]):shuffle([d[2],d[0],d[1]]);if(state.game==='counting'){const v=new Set([d[1]]);while(v.size<n){const delta=Math.floor(Math.random()*3)+1,sign=Math.random()<.5?-1:1;v.add(Math.max(1,Math.min(10,d[1]+sign*delta)))}return shuffle([...v])}if(state.game==='sequence'){const c=d[5],p=['🔴','🔵','🟡','🟢','⭐','❤️','🍎','🍌','🐶','🐱','🚗','🚌','🔺','🍓','🍇','🐟','🐠','☀️','🌙'].filter(x=>x!==c);return shuffle([c,...shuffle(p).slice(0,n-1)])}if(state.game==='size')return shuffle([{emoji:d[0],label:'',key:d[0]},{emoji:d[1],label:'',key:d[1]}]);return shuffle(['GRANDE','PEQUENO'])}
function aylaRenderRound(){const g=games[state.game],d=aylaData();$('questionIcon').textContent=g.icon;$('question').textContent=aylaQuestionText();$('feedback').textContent='';$('feedback').className='feedback';$('progress').style.width=`${state.index/10*100}%`;const visual=$('visual');visual.className='visual';visual.innerHTML='';if(state.game==='memory'){renderMemoryBoard();return}if(namedGames.has(state.game)||state.game==='sounds')visual.textContent=d[0];else if(state.game==='different')visual.textContent=d[0]+'   '+d[1]+'   '+d[2];else if(state.game==='counting')visual.textContent=d[0].repeat(d[1]);else if(state.game==='sequence')visual.textContent=d.slice(0,5).join('  ')+'  ?';else if(state.game==='size')visual.textContent=d[0]+'     '+d[1];const box=$('options');box.innerHTML='';aylaOptions().forEach(v=>{const b=document.createElement('button');b.className=`option ${state.game}-option`;if(v&&typeof v==='object')b.innerHTML=`<span class="option-emoji">${v.emoji}</span><span class="option-label">${v.label}</span>`;else b.textContent=v;b.onclick=()=>aylaAnswer(v,b);box.appendChild(b)})}
function aylaCorrect(){const d=aylaData();if(namedGames.has(state.game)||state.game==='sounds'||state.game==='memory')return d[1];if(state.game==='different')return d[2];if(state.game==='counting')return d[1];if(state.game==='sequence')return d[5];if(state.game==='size')return d[2]==='GRANDE'?d[0]:d[1];return d}
function aylaValue(v){return v&&typeof v==='object'?(v.key??v.label):v}
async function aylaAnswer(value,button){if(state.locked||state.speaking)return;state.locked=true;const chosen=aylaValue(value);if(chosen===aylaCorrect()){button.classList.add('correct');state.score++;applause();$('feedback').textContent='Parabéns, Ayla! Continue assim!';await speak(`Muito bem! É ${answerName(chosen)}! Parabéns, Ayla! Continue assim!`);if(state.index>=9){finishGame();return}state.index++;state.locked=false;await aylaPresentRound()}else{button.classList.add('wrong');$('feedback').textContent='Tente mais uma vez, Ayla!';await speak('Tente mais uma vez, Ayla!');state.locked=false}}
async function aylaPresentRound(){if(!state.game)return;state.locked=true;aylaRenderRound();if(state.game==='sounds'){await new Promise(r=>setTimeout(r,180));state.locked=false;playAnimalSound(aylaData()[1])}else state.locked=false;await speak(aylaQuestionText())}
function aylaBack(){window.speechSynthesis?.cancel();if(animalPlayer){animalPlayer.pause();animalPlayer=null}state.game=null;state.memory=null;state.locked=false;state.speaking=false;$('game').classList.remove('active');$('menu').classList.add('active')}
const aylaButtons=document.querySelectorAll('#gameMenu .game-card');Object.keys(games).forEach((game,i)=>{if(aylaButtons[i])aylaButtons[i].onclick=()=>aylaStartGame(game)});
$('backBtn').onclick=aylaBack;$('repeatBtn').onclick=()=>{if(!state.locked&&!state.speaking)speak(aylaQuestionText())};
