const state={game:null,index:0,score:0,sound:true};
const numberRounds=[1,2,3,4,5,6,7,8,9,10];
const letterRounds=['A','B','C','D','E','F','G','H','I','J'];
const $=id=>document.getElementById(id);

function speak(text){if(!state.sound||!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='pt-BR';u.rate=.88;u.pitch=1.15;window.speechSynthesis.speak(u)}
function applause(){if(!state.sound)return;const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const c=new C(),now=c.currentTime;[0,.12,.24,.36,.48].forEach((t,i)=>{const o=c.createOscillator(),g=c.createGain();o.type='triangle';o.frequency.value=520+i*90;g.gain.setValueAtTime(.0001,now+t);g.gain.exponentialRampToValueAtTime(.16,now+t+.015);g.gain.exponentialRampToValueAtTime(.0001,now+t+.09);o.connect(g).connect(c.destination);o.start(now+t);o.stop(now+t+.1)});setTimeout(()=>c.close(),1000)}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function startGame(game){state.game=game;state.index=0;state.score=0;$('menu').classList.remove('active');$('game').classList.add('active');renderRound();setTimeout(()=>speak(questionText()),250)}
function current(){return (state.game==='numbers'?numberRounds:letterRounds)[state.index]}
function questionText(){return state.game==='numbers'?`Qual é o número ${current()}?`:`Qual é a letra ${current()}?`}
function makeOptions(){const answer=current();const pool=state.game==='numbers'?numberRounds:letterRounds;let wrong;do{wrong=pool[Math.floor(Math.random()*pool.length)]}while(wrong===answer);return shuffle([answer,wrong])}
function renderRound(){const answer=current();$('questionIcon').textContent=state.game==='numbers'?'🔢':'🔤';$('question').textContent=questionText();$('feedback').textContent='';$('feedback').className='feedback';$('progress').style.width=`${state.index/10*100}%`;const box=$('options');box.innerHTML='';makeOptions().forEach(value=>{const b=document.createElement('button');b.className='option';b.textContent=value;b.setAttribute('aria-label',`Opção ${value}`);b.addEventListener('click',()=>answerClick(value,b));box.appendChild(b)})}
function answerClick(value,button){const answer=current();document.querySelectorAll('.option').forEach(b=>b.disabled=true);if(value===answer){state.score++;button.classList.add('correct');applause();$('feedback').textContent='Parabéns, Ayla! Continue assim!';$('feedback').className='feedback success';speak('Parabéns, Ayla! Continue assim!');setTimeout(()=>{state.index++;if(state.index>=10){finishGame()}else{renderRound();setTimeout(()=>speak(questionText()),180)}},1250)}else{button.disabled=false;button.classList.add('wrong');$('feedback').textContent='Tente mais uma vez, Ayla!';$('feedback').className='feedback error';speak('Tente mais uma vez, Ayla!');setTimeout(()=>button.classList.remove('wrong'),450);document.querySelectorAll('.option').forEach(b=>{b.disabled=false})}}
function finishGame(){$('progress').style.width='100%';$('options').innerHTML='<button class="game-card numbers" id="again" style="grid-column:1/-1;min-height:150px"><span class="game-icon">🎉</span><strong>Jogar novamente</strong></button>';$('questionIcon').textContent='🏆';$('question').textContent=`Muito bem, Ayla! Você acertou ${state.score} de 10!`;$('feedback').textContent='Você foi incrível!';$('feedback').className='feedback success';applause();speak(`Muito bem, Ayla! Você acertou ${state.score} de 10! Você foi incrível!`);$('again').addEventListener('click',()=>startGame(state.game))}
document.querySelectorAll('[data-game]').forEach(b=>b.addEventListener('click',()=>startGame(b.dataset.game)));$('backBtn').addEventListener('click',()=>{window.speechSynthesis?.cancel();$('game').classList.remove('active');$('menu').classList.add('active')});$('repeatBtn').addEventListener('click',()=>speak(questionText()));$('soundBtn').addEventListener('click',()=>{state.sound=!state.sound;$('soundBtn').textContent=state.sound?'🔊':'🔇';if(state.sound)speak(questionText());else window.speechSynthesis?.cancel()});
