const state={game:null,index:0,score:0,sound:true,locked:false,speaking:false,memory:null};
const games={
 numbers:{name:'Números',icon:'🔢',cls:'numbers',rounds:[1,2,3,4,5,6,7,8,9,10],q:x=>`Qual é o número ${x}?`},
 letters:{name:'Letras',icon:'🔤',cls:'letters',rounds:['A','B','C','D','E','F','G','H','I','J'],q:x=>`Qual é a letra ${x}?`},
 animals:{name:'Animais',icon:'🐶',cls:'animals',rounds:[['🐶','CACHORRO'],['🐱','GATO'],['🐮','VACA'],['🦁','LEÃO'],['🐘','ELEFANTE'],['🐵','MACACO'],['🐰','COELHO'],['🐔','GALINHA'],['🐟','PEIXE'],['🦋','BORBOLETA']]},
 colors:{name:'Cores',icon:'🎨',cls:'colors',rounds:[['🔴','VERMELHO'],['🔵','AZUL'],['🟡','AMARELO'],['🟢','VERDE'],['🟣','ROXO'],['🟠','LARANJA'],['🩷','ROSA'],['⚫','PRETO'],['⚪','BRANCO'],['🟤','MARROM']]},
 fruits:{name:'Frutas',icon:'🍎',cls:'fruits',rounds:[['🍎','MAÇÃ'],['🍌','BANANA'],['🍊','LARANJA'],['🍉','MELANCIA'],['🍓','MORANGO'],['🍇','UVA'],['🍍','ABACAXI'],['🥭','MANGA'],['🍐','PERA'],['🥝','KIWI']]},
 vehicles:{name:'Veículos',icon:'🚗',cls:'vehicles',rounds:[['🚗','CARRO'],['🚌','ÔNIBUS'],['✈️','AVIÃO'],['🚲','BICICLETA'],['🚂','TREM'],['🚁','HELICÓPTERO'],['🚢','NAVIO'],['🏍️','MOTO'],['🚜','TRATOR'],['🚑','AMBULÂNCIA']]},
 objects:{name:'Objetos',icon:'🧸',cls:'objects',rounds:[['⚽','BOLA'],['🧸','URSO'],['👟','SAPATO'],['🥛','COPO'],['🪥','ESCOVA'],['📚','LIVRO'],['✏️','LÁPIS'],['🎒','MOCHILA'],['🪑','CADEIRA'],['🛏️','CAMA']]},
 shapes:{name:'Formas',icon:'🔷',cls:'shapes',rounds:[['⚪','CÍRCULO'],['🟥','QUADRADO'],['🔺','TRIÂNGULO'],['⭐','ESTRELA'],['💠','LOSANGO'],['⬜','RETÂNGULO'],['❤️','CORAÇÃO'],['🌙','MEIA-LUA'],['🔶','HEXÁGONO'],['🟢','OVAL']]},
 vegetables:{name:'Legumes e Verduras',icon:'🥕',cls:'vegetables',rounds:[['🥕','CENOURA'],['🥦','BRÓCOLIS'],['🌽','MILHO'],['🥒','PEPINO'],['🍅','TOMATE'],['🥔','BATATA'],['🥬','ALFACE'],['🧅','CEBOLA'],['🫑','PIMENTÃO'],['🍆','BERINJELA']]},
 sounds:{name:'Sons',icon:'🔊',cls:'sounds',rounds:[['🐶','CACHORRO'],['🐱','GATO'],['🐮','VACA'],['🐔','GALINHA'],['🐑','OVELHA'],['🦁','LEÃO'],['🐸','SAPO'],['🦆','PATO'],['🐴','CAVALO'],['🐷','PORCO']]},
 memory:{name:'Memória',icon:'🧠',cls:'memory',rounds:[['🍎','MAÇÃ'],['🐶','CACHORRO'],['🚗','CARRO'],['⭐','ESTRELA'],['🍌','BANANA'],['🦋','BORBOLETA'],['⚽','BOLA'],['🌈','ARCO-ÍRIS'],['🐱','GATO'],['❤️','CORAÇÃO']]},
 different:{name:'Qual é diferente?',icon:'🔎',cls:'different',rounds:[['🍎','🍎','🍌'],['🐶','🐶','🐱'],['🔴','🔴','🔵'],['🚗','🚗','🚌'],['⭐','⭐','❤️'],['🍌','🍌','🍎'],['🐱','🐱','🐶'],['🟢','🟢','🟡'],['⚽','⚽','🎈'],['🌸','🌸','🌻']]},
 counting:{name:'Contar Objetos',icon:'🔢',cls:'counting',rounds:[['🍎',1],['⭐',2],['🐶',3],['🍌',4],['❤️',5],['⚽',6],['🌸',7],['🐟',8],['🍓',9],['🌈',10]]},
 sequence:{name:'Sequência',icon:'🧩',cls:'sequence',rounds:[['🔴','🔵','🔴','🔵','🔴','🔵'],['⭐','❤️','⭐','❤️','⭐','❤️'],['🍎','🍌','🍎','🍌','🍎','🍌'],['🐶','🐱','🐶','🐱','🐶','🐱'],['🟢','🟡','🟢','🟡','🟢','🟡'],['🚗','🚌','🚗','🚌','🚗','🚌'],['🔺','🟢','🔺','🟢','🔺','🟢'],['🍓','🍇','🍓','🍇','🍓','🍇'],['🐟','🐠','🐟','🐠','🐟','🐠'],['☀️','🌙','☀️','🌙','☀️','🌙']]},
 size:{name:'Grande ou Pequeno?',icon:'📏',cls:'size',rounds:[['🐘','🐭','GRANDE'],['🍉','🍓','GRANDE'],['🚌','🚲','GRANDE'],['🦁','🐜','GRANDE'],['🌳','🌱','GRANDE'],['🐭','🐘','PEQUENO'],['🍓','🍉','PEQUENO'],['🚲','🚌','PEQUENO'],['🐜','🦁','PEQUENO'],['🌱','🌳','PEQUENO']]}
};
const $=id=>document.getElementById(id),shuffle=a=>[...a].sort(()=>Math.random()-.5),namedGames=new Set(['animals','colors','fruits','vehicles','objects','shapes','vegetables']);
function getFriendlyVoice(){if(!('speechSynthesis'in window))return null;const voices=window.speechSynthesis.getVoices(),pt=voices.filter(v=>/^pt(-|_)/i.test(v.lang));return pt.find(v=>/Francisca|Maria|Helena|female|feminina|mulher/i.test(v.name))||pt.find(v=>/pt-BR/i.test(v.lang))||pt[0]||null}
function speak(text){if(!state.sound||!('speechSynthesis'in window))return Promise.resolve();window.speechSynthesis.cancel();state.speaking=true;return new Promise(resolve=>{const u=new SpeechSynthesisUtterance(text);u.lang='pt-BR';u.rate=.82;u.pitch=1.12;u.volume=1;const voice=getFriendlyVoice();if(voice)u.voice=voice;let done=false;const finish=()=>{if(done)return;done=true;state.speaking=false;resolve()};u.onend=finish;u.onerror=finish;window.speechSynthesis.speak(u);setTimeout(finish,Math.max(5000,text.length*140))})}
function applause(){if(!state.sound)return;const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const c=new C(),n=c.currentTime;[0,.12,.24,.36,.48].forEach((t,i)=>{const o=c.createOscillator(),g=c.createGain();o.type='triangle';o.frequency.value=520+i*90;g.gain.setValueAtTime(.0001,n+t);g.gain.exponentialRampToValueAtTime(.16,n+t+.015);g.gain.exponentialRampToValueAtTime(.0001,n+t+.09);o.connect(g).connect(c.destination);o.start(n+t);o.stop(n+t+.1)});setTimeout(()=>c.close(),1000)}
const animalAudio={CACHORRO:'https://commons.wikimedia.org/wiki/Special:FilePath/Dog_barking.webm',GATO:'https://commons.wikimedia.org/wiki/Special:FilePath/Meow.ogg',VACA:'https://commons.wikimedia.org/wiki/Special:FilePath/Single_Cow_Moo.ogg',OVELHA:'https://commons.wikimedia.org/wiki/Special:FilePath/Sheep_bleat.ogg',SAPO:'https://commons.wikimedia.org/wiki/Special:FilePath/Frog_sounds.ogg',PATO:'https://commons.wikimedia.org/wiki/Special:FilePath/En-us-duck.ogg',PORCO:'https://commons.wikimedia.org/wiki/Special:FilePath/Domestic_pig_grunting.webm'};
let animalPlayer=null;
function playAnimalSound(animal){if(!state.sound)return Promise.resolve();if(animalPlayer){animalPlayer.pause();animalPlayer.currentTime=0}const url=animalAudio[animal];if(!url)return Promise.resolve();animalPlayer=new Audio(url);animalPlayer.volume=.9;animalPlayer.preload='auto';return new Promise(resolve=>{let done=false;const finish=()=>{if(done)return;done=true;resolve()};animalPlayer.onended=finish;animalPlayer.onerror=finish;animalPlayer.play().catch(finish);setTimeout(finish,4200)})}
function buildMenu(){const box=$('gameMenu');box.innerHTML='';Object.entries(games).forEach(([key,g])=>{const b=document.createElement('button');b.className=`game-card ${g.cls}`;b.innerHTML=`<span class="game-icon">${g.icon}</span><strong>${g.name}</strong><small>Vamos brincar!</small>`;b.onclick=()=>startGame(key);box.appendChild(b)})}
function startGame(game){window.speechSynthesis?.cancel();if(animalPlayer){animalPlayer.pause();animalPlayer=null}state.game=game;state.index=0;state.score=0;state.locked=false;state.speaking=false;state.memory=null;$('menu').classList.remove('active');$('game').classList.add('active');setTimeout(()=>presentRound(),120)}
function difficulty(){return state.index<3?2:state.index<6?3:4}
function data(){return games[state.game].rounds[state.index]}
function questionText(){const g=games[state.game],d=data();if(state.game==='numbers'||state.game==='letters')return g.q(d);const questions={animals:'Que animal é esse?',colors:'Que cor é essa?',fruits:'Que fruta é essa?',vehicles:'Que veículo é esse?',objects:'Que objeto é esse?',shapes:'Que forma é essa?',vegetables:'Que legume ou verdura é essa?'};if(questions[state.game])return questions[state.game];if(state.game==='sounds')return 'Ouça o som! Qual animal faz esse som?';if(state.game==='memory')return 'Encontre os pares!';if(state.game==='different')return 'Qual é o diferente?';if(state.game==='counting')return 'Quantos objetos você vê?';if(state.game==='sequence')return 'O que vem depois?';return `Qual é o ${d[2].toLowerCase()}?`}
function makeOptions(){const d=data(),g=games[state.game],n=difficulty();if(state.game==='numbers'||state.game==='letters'){const pool=g.rounds.filter(x=>x!==d);return shuffle([d,...shuffle(pool).slice(0,n-1)])}if(namedGames.has(state.game)){const pool=shuffle(g.rounds.filter(x=>x[1]!==d[1]));return shuffle([d,...pool.slice(0,n-1)]).map(x=>({emoji:x[0],label:x[1],key:x[1]}))}if(state.game==='sounds'){const pool=shuffle(g.rounds.filter(x=>x[1]!==d[1]));return shuffle([d,...pool.slice(0,n-1)]).map(x=>({emoji:x[0],label:x[1],key:x[1]}))}if(state.game==='different')return n===2?shuffle([d[2],d[0]]):shuffle([d[2],d[0],d[1]]);if(state.game==='counting'){const vals=new Set([d[1]]);while(vals.size<n){const delta=Math.floor(Math.random()*3)+1,sign=Math.random()<.5?-1:1,v=Math.max(1,Math.min(10,d[1]+sign*delta));vals.add(v)}return shuffle([...vals])}if(state.game==='sequence'){const correct=d[5],candidates=['🔴','🔵','🟡','🟢','⭐','❤️','🍎','🍌','🐶','🐱','🚗','🚌','🔺','🍓','🍇','🐟','🐠','☀️','🌙'].filter(x=>x!==correct);return shuffle([correct,...shuffle(candidates).slice(0,n-1)])}if(state.game==='size')return shuffle([{emoji:d[0],label:'',key:d[0]},{emoji:d[1],label:'',key:d[1]}]);return shuffle(['GRANDE','PEQUENO'])}
function renderRound(){const g=games[state.game],d=data();$('questionIcon').textContent=g.icon;$('question').textContent=questionText();$('feedback').textContent='';$('feedback').className='feedback';$('progress').style.width=`${state.index/10*100}%`;const visual=$('visual');visual.className='visual';visual.innerHTML='';if(state.game==='memory'){renderMemoryBoard();return}if(namedGames.has(state.game)||state.game==='sounds')visual.textContent=d[0];else if(state.game==='different')visual.textContent=d[0]+'   '+d[1]+'   '+d[2];else if(state.game==='counting')visual.textContent=d[0].repeat(d[1]);else if(state.game==='sequence')visual.textContent=d.slice(0,5).join('  ')+'  ?';else if(state.game==='size')visual.textContent=d[0]+'     '+d[1];const box=$('options');box.innerHTML='';makeOptions().forEach(v=>{const b=document.createElement('button');b.className=`option ${state.game}-option`;if(v&&typeof v==='object')b.innerHTML=`<span class="option-emoji">${v.emoji}</span><span class="option-label">${v.label}</span>`;else b.textContent=v;b.onclick=()=>answerClick(v,b);box.appendChild(b)})}
function renderMemoryBoard(){const visual=$('visual'),box=$('options');box.innerHTML='';visual.className='visual memory-board';if(!state.memory){const count=state.index<3?2:state.index<6?3:4;const bank=shuffle(games.memory.rounds).slice(0,count);const cards=shuffle(bank.flatMap(x=>[{id:x[1],emoji:x[0],label:x[1],pair:x[1]},{id:x[1],emoji:x[0],label:x[1],pair:x[1]}])).map((x,i)=>({...x,index:i}));state.memory={cards,flipped:[],matched:new Set()}}state.memory.cards.forEach(card=>{const b=document.createElement('button');b.className='memory-card';b.dataset.index=card.index;if(state.memory.flipped.includes(card.index)||state.memory.matched.has(card.pair))b.classList.add('flipped');b.innerHTML=`<span class="memory-back">❓</span><span class="memory-front">${card.emoji}</span>`;b.onclick=()=>memoryClick(card.index,b);visual.appendChild(b)})}
async function memoryClick(index,button){if(state.locked||state.speaking)return;const m=state.memory,card=m.cards[index];if(!card||m.matched.has(card.pair)||m.flipped.includes(index)||m.flipped.length>=2)return;m.flipped.push(index);button.classList.add('flipped');if(m.flipped.length===1){await new Promise(r=>setTimeout(r,260));return}state.locked=true;const a=m.cards[m.flipped[0]],b=m.cards[m.flipped[1]];if(a.pair===b.pair){m.matched.add(a.pair);m.flipped=[];state.score++;applause();$('feedback').textContent='Muito bem! Você encontrou um par!';await speak('Muito bem! Você encontrou um par!');state.locked=false;if(m.matched.size===m.cards.length/2)await finishRound()}else{await speak('Tente mais uma vez!');await new Promise(r=>setTimeout(r,650));m.flipped=[];renderMemoryBoard();state.locked=false}}
function correctValue(){const d=data();if(namedGames.has(state.game)||state.game==='sounds'||state.game==='memory')return d[1];if(state.game==='different')return d[2];if(state.game==='counting')return d[1];if(state.game==='sequence')return d[5];if(state.game==='size')return d[2]==='GRANDE'?d[0]:d[1];return d}
function answerName(v){if(state.game==='numbers')return `o número ${v}`;if(state.game==='letters')return `a letra ${v}`;if(state.game==='different')return 'o diferente';if(state.game==='counting')return `o número ${v}`;if(state.game==='sequence'){const names={'🔴':'vermelho','🔵':'azul','🟡':'amarelo','🟢':'verde','⭐':'estrela','❤️':'coração','🍎':'maçã','🍌':'banana','🐶':'cachorro','🐱':'gato','🚗':'carro','🚌':'ônibus','🔺':'triângulo','🍓':'morango','🍇':'uva','🐟':'peixe','🐠':'peixinho','☀️':'sol','🌙':'lua'};return names[v]||v}if(state.game==='size')return data()[2].toLowerCase();if(state.game==='sounds'||namedGames.has(state.game))return String(v).toLowerCase();return String(v).toLowerCase()}
async function answerClick(value,button){if(state.locked||state.speaking)return;state.locked=true;const chosen=answerValue(value),correct=correctValue();if(chosen===correct){button.classList.add('correct');state.score++;applause();$('feedback').textContent='Parabéns, Ayla! Continue assim!';await speak(`Muito bem! É ${answerName(chosen)}! Parabéns, Ayla! Continue assim!`);await finishRound()}else{button.classList.add('wrong');$('feedback').textContent='Tente mais uma vez, Ayla!';await speak('Tente mais uma vez, Ayla!');state.locked=false}}
function answerValue(v){return v&&typeof v==='object'?(v.key??v.label):v}
async function finishRound(){state.locked=true;await new Promise(r=>setTimeout(r,300));if(state.index>=9){finishGame();return}state.index++;state.memory=null;state.locked=false;await presentRound()}
function finishGame(){$('progress').style.width='100%';$('options').innerHTML='<button class="game-card numbers" id="again" style="grid-column:1/-1;min-height:130px"><span class="game-icon">🎉</span><strong>Jogar novamente</strong></button>';$('visual').innerHTML='🏆 ⭐ ⭐ ⭐';$('questionIcon').textContent='🏆';$('question').textContent=`Muito bem, Ayla! Você acertou ${state.score} de 10!`;$('feedback').textContent='Você foi incrível!';$('feedback').className='feedback success';applause();speak(`Muito bem, Ayla! Você acertou ${state.score} de 10!`);$('again').onclick=()=>startGame(state.game)}
function backToMenu(){window.speechSynthesis?.cancel();if(animalPlayer){animalPlayer.pause();animalPlayer=null}state.game=null;state.memory=null;state.locked=false;state.speaking=false;$('game').classList.remove('active');$('menu').classList.add('active')}
if('speechSynthesis'in window)window.speechSynthesis.onvoiceschanged=()=>getFriendlyVoice();buildMenu();$('backBtn').onclick=backToMenu;$('repeatBtn').onclick=()=>{if(!state.locked&&!state.speaking)speak(questionText())};$('soundBtn').onclick=()=>{state.sound=!state.sound;$('soundBtn').textContent=state.sound?'🔊':'🔇';if(state.sound)speak(questionText());else window.speechSynthesis?.cancel()};